# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161011_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
